# Project 3

#### Importing Packages and Loading the Data

In [1]:
import datetime
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
%matplotlib inline


# Overrides pandas default display option that limits number of columns displayed
pd.set_option("display.max_columns",999)
pd.set_option('precision',2)

In [2]:
df = pd.read_csv("Iowa_Liquor_sales_sample_10pct.csv")
df.head(5)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,11/04/2015,3717,SUMNER,50674,9.0,Bremer,1.05e+06,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,$4.50,$6.75,12,$81.00,9.0,2.38
1,03/02/2016,2614,DAVENPORT,52807,82.0,Scott,1.01e+06,BLENDED WHISKIES,395,27605,Tin Cup,750,$13.75,$20.63,2,$41.26,1.5,0.40
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.0,6.34
3,02/03/2016,2501,AMES,50010,85.0,Story,1.07e+06,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,$9.50,$14.25,6,$85.50,10.5,2.77
4,08/18/2015,3654,BELMOND,50421,99.0,Wright,1.03e+06,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,$7.20,$10.80,12,$129.60,21.0,5.55

In [3]:
df.shape

(270955, 18)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270955 entries, 0 to 270954
Data columns (total 18 columns):
Date                     270955 non-null object
Store Number             270955 non-null int64
City                     270955 non-null object
Zip Code                 270955 non-null object
County Number            269878 non-null float64
County                   269878 non-null object
Category                 270887 non-null float64
Category Name            270323 non-null object
Vendor Number            270955 non-null int64
Item Number              270955 non-null int64
Item Description         270955 non-null object
Bottle Volume (ml)       270955 non-null int64
State Bottle Cost        270955 non-null object
State Bottle Retail      270955 non-null object
Bottles Sold             270955 non-null int64
Sale (Dollars)           270955 non-null object
Volume Sold (Liters)     270955 non-null float64
Volume Sold (Gallons)    270955 non-null float64
dtypes: float64(4), int64(5), object(9)
memory usage: 37.2+ MB

In [5]:
# Code to get the number of unique values per column

header = list(df.columns.values)
unique = [(c, df[c].nunique()) for c in header]
unique

[('Date', 274),
 ('Store Number', 1400),
 ('City', 385),
 ('Zip Code', 415),
 ('County Number', 99),
 ('County', 99),
 ('Category', 83),
 ('Category Name', 71),
 ('Vendor Number', 116),
 ('Item Number', 2696),
 ('Item Description', 2173),
 ('Bottle Volume (ml)', 29),
 ('State Bottle Cost', 1086),
 ('State Bottle Retail', 1112),
 ('Bottles Sold', 137),
 ('Sale (Dollars)', 6580),
 ('Volume Sold (Liters)', 265),
 ('Volume Sold (Gallons)', 261)]

Start with a data set of 1400 stores - from the unique store numbers

#### Seeing what the data is like aggregated at the store level 

Store Number 5128 is in Des Moines

In [6]:
test_store2106 = df[df['Store Number']==2106]
test_store2106

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
2,02/11/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,$12.59,$18.89,24,$453.36,24.00,6.34
1161,08/20/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,IMPORTED VODKA,370,34007,Absolut Swedish Vodka 80 Prf,1000,$14.99,$22.49,36,$809.64,36.00,9.51
1410,01/14/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.70e+06,DECANTERS & SPECIALTY PACKAGES,65,789,Canadian Club w/Glass,750,$7.88,$11.82,12,$141.84,9.00,2.38
1525,03/12/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,STRAIGHT BOURBON WHISKIES,85,22216,Woodford Reserve Bourbon,750,$21.02,$31.53,6,$189.18,4.50,1.19
1869,02/11/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,VODKA 80 PROOF,55,35317,Barton Vodka,1000,$3.97,$5.96,180,$1072.80,180.00,47.55
2348,07/30/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,IMPORTED SCHNAPPS,260,69947,Rumple Minze Peppermint Schnapps Liqueur,1000,$15.75,$23.63,12,$283.56,12.00,3.17
2512,01/22/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.04e+06,AMERICAN DRY GINS,434,30527,Hawkeye Gin,1000,$4.23,$6.35,12,$76.20,12.00,3.17
2663,08/13/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,GRAPE SCHNAPPS,65,82637,Dekuyper Grape Pucker,1000,$7.62,$11.43,12,$137.16,12.00,3.17
3080,02/04/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,JAPANESE WHISKY,370,15667,Jameson Black Barrel,750,$17.49,$26.24,12,$314.88,9.00,2.38
3298,03/03/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,MISC. AMERICAN CORDIALS & LIQUEURS,65,85526,Dekuyper Signature Blue Curacao,750,$5.25,$7.88,12,$94.56,9.00,2.38
3433,12/03/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,TRIPLE SEC,421,86637,Tortilla Triple Sec,1000,$3.01,$4.52,12,$54.24,12.00,3.17
3827,01/07/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,STRAIGHT BOURBON WHISKIES,65,27410,Jim Beam Honey,750,$10.49,$15.74,12,$188.88,9.00,2.38
4442,10/08/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.02e+06,TEQUILA,395,89197,Jose Cuervo Especial Reposado Tequila,1000,$12.50,$18.75,24,$450.00,24.00,6.34
4814,10/29/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.06e+06,SPICED RUM,259,43026,Admiral Nelson Spiced Rum,750,$5.78,$8.67,12,$104.04,9.00,2.38
4843,04/16/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,VODKA 80 PROOF,260,37997,Smirnoff Vodka 80 Prf,1000,$9.25,$13.88,12,$166.56,12.00,3.17
5511,09/03/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,STRAWBERRY SCHNAPPS,434,84496,Paramount Strawberry Schnapps,750,$4.75,$7.13,12,$85.56,9.00,2.38
5879,02/04/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.07e+06,AMERICAN COCKTAILS,421,59037,Desert Island Long Island Ice Tea Cocktail,1000,$3.86,$6.04,24,$144.96,24.00,6.34
6065,05/07/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,CREAM LIQUEURS,260,68037,Bailey's Original Irish Cream,1000,$17.25,$25.88,12,$310.56,12.00,3.17
7326,05/21/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.02e+06,TEQUILA,205,89533,Familia Camarena Reposado,750,$10.00,$15.00,5,$75.00,3.75,0.99
7469,02/12/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.04e+06,AMERICAN DRY GINS,297,29997,Five O'clock Gin,1000,$4.33,$6.50,12,$78.00,12.00,3.17
8256,06/18/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.06e+06,FLAVORED RUM,35,43117,Bacardi O,1000,$9.50,$14.25,12,$171.00,12.00,3.17
8741,08/27/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,IRISH WHISKIES,370,15627,Jameson,1000,$18.49,$27.74,24,$665.76,24.00,6.34
8881,07/16/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,IMPORTED VODKA - MISC,395,34959,Three Olives Raspberry Vodka,750,$9.96,$14.94,2,$29.88,1.50,0.40
9057,04/09/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,VODKA FLAVORED,300,41019,360 Double Chocolate Vodka,750,$7.00,$10.50,2,$21.00,1.50,0.40
9277,09/17/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.06e+06,SPICED RUM,260,43336,Captain Morgan Original Spiced,750,$9.00,$13.50,12,$162.00,9.00,2.38
9334,07/09/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,STRAIGHT BOURBON WHISKIES,434,18196,Ezra Brooks 50 Mo Ky Sour Mash Bourbon,750,$6.84,$10.26,2,$20.52,1.50,0.40
9503,12/03/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,TRIPLE SEC,434,86251,Juarez Triple Sec,1000,$2.42,$3.63,48,$174.24,48.00,12.68
9943,03/24/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,PEACH SCHNAPPS,65,82847,Dekuyper Peachtree,1000,$7.87,$11.81,12,$141.72,12.00,3.17
10012,08/20/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,BLENDED WHISKIES,260,27554,Seagrams Seven Crown Dark Honey,750,$7.00,$10.50,24,$252.00,18.00,4.76
10232,08/27/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.04e+06,AMERICAN DRY GINS,125,29812,Clearheart Gin,750,$12.30,$18.45,6,$110.70,4.50,1.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257170,07/16/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,PEACH SCHNAPPS,65,82847,Dekuyper Peachtree,1000,$7.62,$11.43,12,$137.16,12.00,3.17
257182,10/22/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,CANADIAN WHISKIES,115,10553,Black Velvet Cinnamon Rush,750,$6.75,$10.13,12,$121.56,9.00,2.38
257998,11/19/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,CANADIAN WHISKIES,115,11788,Black Velvet,1750,$10.45,$15.68,12,$188.16,21.00,5.55
258145,01/29/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,SCOTCH WHISKIES,55,8826,Lauder's Scotch,750,$5.13,$7.70,12,$92.40,9.00,2.38
258682,09/03/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,BLENDED WHISKIES,65,25877,Sunny Brook Blend Whiskey,1000,$4.46,$6.69,4,$26.76,4.00,1.06
258867,12/10/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.04e+06,AMERICAN DRY GINS,55,29287,Barton Gin,1000,$3.92,$5.88,12,$70.56,12.00,3.17
259810,12/17/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,DISTILLED SPIRITS SPECIALTY,434,75087,Juarez Gold Dss,1000,$4.92,$7.38,24,$177.12,24.00,6.34
260397,10/22/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,MISC. IMPORTED CORDIALS & LIQUEURS,240,64876,Drambuie Liqueur,750,$21.00,$31.50,12,$378.00,9.00,2.38
261014,11/05/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,IMPORTED VODKA - MISC,434,35699,Pearl Cucumber Vodka,750,$7.00,$10.50,24,$252.00,18.00,4.76
261146,04/09/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,IMPORTED SCHNAPPS,260,904563,Black Haus Blackberry Schnapps,1000,$15.00,$22.50,12,$270.00,12.00,3.17
262665,05/07/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,VODKA FLAVORED,380,41783,Uv Blue Raspberry Vodka Mini,500,$4.89,$7.34,1,$7.34,0.50,0.13
262951,03/03/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,VODKA 80 PROOF,300,36887,McCormick Vodka,1000,$4.13,$6.20,12,$74.40,12.00,3.17
263748,08/13/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,CANADIAN WHISKIES,115,11776,Black Velvet,750,$5.23,$7.85,24,$188.40,18.00,4.76
264276,02/26/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.70e+06,DECANTERS & SPECIALTY PACKAGES,35,1649,Bacardi 8 w/2 Glasses,750,$10.50,$15.75,6,$94.50,4.50,1.19
265854,01/29/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.03e+06,IMPORTED VODKA,370,34006,Absolut Swedish Vodka 80 Prf,750,$11.49,$17.24,24,$413.76,18.00,4.76
265989,02/19/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,IMPORTED SCHNAPPS,260,69947,Rumple Minze Peppermint Schnapps Liqueur,1000,$15.75,$23.63,24,$567.12,24.00,6.34
266183,12/10/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,IMPORTED SCHNAPPS,260,69946,Rumple Minze Peppermint Schnapps Liqueur,750,$13.00,$19.50,12,$234.00,9.00,2.38
266293,03/19/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,IRISH WHISKIES,240,15940,Tullamore Dew Irish Whisky,750,$14.38,$21.57,24,$517.68,18.00,4.76
267232,02/18/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,IRISH WHISKIES,420,900179,Glenmorangie Milsean HA,750,$49.99,$74.99,3,$224.97,2.25,0.59
267319,02/26/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.06e+06,PUERTO RICO & VIRGIN ISLANDS RUM,434,45277,Paramount White Rum,1000,$4.34,$6.51,48,$312.48,48.00,12.68
267521,12/10/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,BLENDED WHISKIES,297,23827,Five Star,1000,$4.40,$6.60,24,$158.40,24.00,6.34
267683,02/26/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,BUTTERSCOTCH SCHNAPPS,65,82787,Dekuyper Buttershots,1000,$7.62,$11.43,12,$137.16,12.00,3.17
268060,06/25/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.04e+06,AMERICAN DRY GINS,434,31657,Paramount Gin,1000,$4.30,$6.45,12,$77.40,12.00,3.17
268943,01/28/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.02e+06,TEQUILA,421,89916,Tortilla Gold Tequila,750,$6.20,$9.30,12,$111.60,9.00,2.38
268995,12/10/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,CANADIAN WHISKIES,115,11776,Black Velvet,750,$5.23,$7.85,12,$94.20,9.00,2.38
269246,09/24/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,WHISKEY LIQUEUR,421,64867,Fireball Cinnamon Whiskey,1000,$11.34,$17.01,72,$1224.72,72.00,19.02
269681,10/15/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.06e+06,PUERTO RICO & VIRGIN ISLANDS RUM,434,45277,Paramount White Rum,1000,$4.34,$6.51,48,$312.48,48.00,12.68
269813,05/14/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.08e+06,MISC. IMPORTED CORDIALS & LIQUEURS,192,65256,Jagermeister Liqueur,750,$12.05,$18.08,12,$216.96,9.00,2.38
270254,07/01/2015,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.01e+06,IRISH WHISKIES,370,15627,Jameson,1000,$18.49,$27.74,24,$665.76,24.00,6.34
270442,01/28/2016,2106,CEDAR FALLS,50613,7.0,Black Hawk,1.06e+06,FLAVORED RUM,65,44350,Calico Jack Cherry,750,$6.30,$9.45,2,$18.90,1.50,0.40

In [7]:
test_store2106.shape

(654, 18)

In [8]:
header = list(test_store2106.columns.values)
unique = [(c, test_store2106[c].nunique()) for c in header]
unique

[('Date', 65),
 ('Store Number', 1),
 ('City', 1),
 ('Zip Code', 1),
 ('County Number', 1),
 ('County', 1),
 ('Category', 52),
 ('Category Name', 50),
 ('Vendor Number', 33),
 ('Item Number', 281),
 ('Item Description', 248),
 ('Bottle Volume (ml)', 6),
 ('State Bottle Cost', 199),
 ('State Bottle Retail', 197),
 ('Bottles Sold', 19),
 ('Sale (Dollars)', 301),
 ('Volume Sold (Liters)', 32),
 ('Volume Sold (Gallons)', 32)]

In [9]:
test_store2106['Bottles Sold'].max()

180

In [10]:
test_store2106['Bottles Sold'].min()

1

## Cleaning the data

Task List:
* Remove "$" prices from characters and convert values to floats.
* Convert dates to pandas datetime objects
* Convert category floats to integers
* Drop or fill in bad values

##### Remove "$" prices from characters and convert values to floats

In [11]:
dollar_removal_cols = ["State Bottle Cost", "State Bottle Retail", "Sale (Dollars)"]

for col in dollar_removal_cols:
    df[col] = df[col].apply(lambda x: float(x[1:]))

In [12]:
df.head(2)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,11/04/2015,3717,SUMNER,50674,9.0,Bremer,1.05e+06,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,4.50,6.75,12,81.00,9.0,2.38
1,03/02/2016,2614,DAVENPORT,52807,82.0,Scott,1.01e+06,BLENDED WHISKIES,395,27605,Tin Cup,750,13.75,20.63,2,41.26,1.5,0.40

##### Convert dates to pandas datetime objects

In [13]:
df["Date"] = pd.to_datetime(df["Date"], format="%m/%d/%Y")
df.head(2)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,2015-11-04,3717,SUMNER,50674,9.0,Bremer,1.05e+06,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,4.50,6.75,12,81.00,9.0,2.38
1,2016-03-02,2614,DAVENPORT,52807,82.0,Scott,1.01e+06,BLENDED WHISKIES,395,27605,Tin Cup,750,13.75,20.63,2,41.26,1.5,0.40

In [14]:
df["Date"].max()

Timestamp('2016-03-31 00:00:00')

In [15]:
df["Date"].min()

Timestamp('2015-01-05 00:00:00')

##### Drop or replace 'bad' values

In [16]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 269258 entries, 0 to 270954
Data columns (total 18 columns):
Date                     269258 non-null datetime64[ns]
Store Number             269258 non-null int64
City                     269258 non-null object
Zip Code                 269258 non-null object
County Number            269258 non-null float64
County                   269258 non-null object
Category                 269258 non-null float64
Category Name            269258 non-null object
Vendor Number            269258 non-null int64
Item Number              269258 non-null int64
Item Description         269258 non-null object
Bottle Volume (ml)       269258 non-null int64
State Bottle Cost        269258 non-null float64
State Bottle Retail      269258 non-null float64
Bottles Sold             269258 non-null int64
Sale (Dollars)           269258 non-null float64
Volume Sold (Liters)     269258 non-null float64
Volume Sold (Gallons)    269258 non-null float64
dtypes: datetime64[ns](1), float64(7), int64(5), object(5)
memory usage: 39.0+ MB

In [17]:
# of stores after dropna drops from 1400 to 1378

df['Store Number'].nunique()

1378

In [18]:
df['Zip Code'].nunique()

412

##### Convert category floats to integers

In [19]:
df["County Number"] = df["County Number"].astype(int)
df["Category"] = df["Category"].astype(int)
df.head(2)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,2015-11-04,3717,SUMNER,50674,9,Bremer,1051100,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,4.50,6.75,12,81.00,9.0,2.38
1,2016-03-02,2614,DAVENPORT,52807,82,Scott,1011100,BLENDED WHISKIES,395,27605,Tin Cup,750,13.75,20.63,2,41.26,1.5,0.40

### At this point now that everything has been converted to numbers should look at outliers

In [20]:
df.describe()

,Store Number,County Number,Category,Vendor Number,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
count,269258.00,269258.00,2.69e+05,269258.00,269258.00,269258.00,269258.00,269258.00,269258.00,269258.00,269258.00,269258.00
mean,3587.70,57.23,1.04e+06,256.36,45944.81,925.22,9.76,14.66,9.87,128.83,8.99,2.38
std,946.51,27.34,5.02e+04,140.98,52557.19,492.84,7.04,10.56,24.07,383.48,28.96,7.65
min,2106.00,1.00,1.01e+06,10.00,168.00,50.00,0.89,1.34,1.00,1.34,0.10,0.03
25%,2604.00,31.00,1.01e+06,115.00,26827.00,750.00,5.50,8.25,2.00,30.42,1.50,0.40
50%,3721.00,62.00,1.03e+06,260.00,38176.00,750.00,8.00,12.11,6.00,70.56,5.25,1.39
75%,4376.00,77.00,1.06e+06,380.00,64573.00,1000.00,11.92,17.88,12.00,135.00,10.50,2.77
max,9023.00,99.00,1.70e+06,978.00,995507.00,6000.00,425.00,637.50,2508.00,36392.40,2508.00,662.54

In [21]:
df.shape

(269258, 18)

In [22]:
# Top percentile of bottle sales

df['Bottles Sold'].quantile(.99)

60.0

In [23]:
wholesale_df = df[df['Bottles Sold'] >= 75]

In [24]:
wholesale_df.shape # of of transactions that involved > 85 bottles sold

(2101, 18)

In [25]:
# how to calculate number of observations eliminated if you limit transaction sizes to x percentile

pct_of_total_obs_elim = (wholesale_df.shape[0]*1.0 / df.shape[0])*100
pct_of_total_obs_elim

0.780292507557807

In [26]:
df_less_ws = df[df['Bottles Sold'] <= 75]

In [27]:
df_less_ws.shape

(267158, 18)

In [28]:
df_less_ws.describe()

,Store Number,County Number,Category,Vendor Number,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
count,267158.00,267158.00,2.67e+05,267158.00,267158.00,267158.00,267158.00,267158.00,267158.00,267158.00,267158.00,267158.00
mean,3587.76,57.19,1.04e+06,256.35,45925.21,924.28,9.76,14.66,8.44,107.81,7.39,1.95
std,946.07,27.35,5.00e+04,140.98,52326.14,492.51,7.05,10.57,9.18,141.54,8.79,2.32
min,2106.00,1.00,1.01e+06,10.00,168.00,50.00,0.89,1.34,1.00,1.34,0.10,0.03
25%,2604.00,31.00,1.01e+06,115.00,26827.00,750.00,5.50,8.27,2.00,30.06,1.50,0.40
50%,3721.00,62.00,1.03e+06,260.00,38176.00,750.00,8.00,12.00,6.00,69.60,5.25,1.39
75%,4376.00,77.00,1.06e+06,380.00,64573.00,1000.00,11.88,17.82,12.00,134.88,10.50,2.77
max,9023.00,99.00,1.70e+06,978.00,995507.00,6000.00,425.00,637.50,75.00,3712.50,153.00,40.42

In [29]:
# Top percentile of retail price

df['State Bottle Retail'].quantile(.999)

98.989999999999995

In [30]:
topshelf_df =  df[df['State Bottle Retail'] >= 100]
topshelf_df.shape

(220, 18)

In [31]:
pct_of_total_obs_elim = (topshelf_df.shape[0]*1.0 / df.shape[0])*100
pct_of_total_obs_elim

0.08170602173380177

### Taking Out the Outliers on Wholesale and Top Shelf

In [32]:
df = df[df['Bottles Sold'] <= 75]

In [33]:
df.shape

(267158, 18)

In [34]:
df = df[df['State Bottle Retail'] <= 100]

In [35]:
df.shape

(266938, 18)

In [36]:
df.describe()

,Store Number,County Number,Category,Vendor Number,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
count,266938.00,266938.00,2.67e+05,266938.00,266938.0,266938.00,266938.00,266938.00,266938.00,266938.00,266938.00,266938.00
mean,3587.98,57.19,1.04e+06,256.31,45735.0,924.21,9.68,14.53,8.44,107.59,7.39,1.95
std,946.02,27.35,5.00e+04,141.00,50561.2,491.78,6.29,9.43,9.18,140.61,8.79,2.32
min,2106.00,1.00,1.01e+06,10.00,168.0,50.00,0.89,1.34,1.00,1.34,0.10,0.03
25%,2604.00,31.00,1.01e+06,115.00,26827.0,750.00,5.50,8.25,2.00,30.04,1.50,0.40
50%,3721.00,62.00,1.03e+06,260.00,38176.0,750.00,8.00,12.00,6.00,69.57,5.25,1.39
75%,4377.00,77.00,1.06e+06,380.00,64573.0,1000.00,11.83,17.75,12.00,134.88,10.50,2.77
max,9023.00,99.00,1.70e+06,978.00,994945.0,4800.00,65.99,98.99,75.00,3429.36,153.00,40.42

In [37]:
# of stores after eliminating outliers - remains virtually the same - 1378 to 1377

df['Store Number'].nunique()

1377

## Filter the Data

Some stores may have opened or closed in 2015. These data points will heavily skew our models, so we need to filter them out or find a way to deal with them.

You'll need to provide a summary in your project report about these data points. You may also consider using the monthly sales in your model and including other information (number of months or days each store is open) in your data to handle these unusual cases.

Let's record the first and last sales dates for each store. We'll save this information for later when we fit our models.

##### Determine which stores were open all of 2015 - finding the first and last sale date

In [38]:
dates = df.groupby(by=["Store Number"], as_index=False)
dates = dates.agg({"Date": [np.min, np.max]})

##### For formatting purposes, this strips the empty cell above the first row

In [39]:
dates.columns = [' '.join(col).strip() for col in dates.columns.values]
dates.head()

   Store Number  Date amin  Date amax
0          2106 2015-01-08 2016-03-31
1          2113 2015-01-07 2016-03-23
2          2130 2015-01-08 2016-03-31
3          2152 2015-01-08 2016-02-25
4          2178 2015-01-07 2016-03-30

##### This code filters out stores that opened or closed during 2015 using a mask

Stores that opened after March 1st and stores that closed before October 1 are to be considered partial year stores

In [40]:
lower_cutoff = pd.Timestamp("20150301")
upper_cutoff = pd.Timestamp("20151001")

mask = (dates['Date amin'] < lower_cutoff) & (dates['Date amax'] > upper_cutoff)

good_stores = dates[mask]["Store Number"]

In [41]:
good_stores.nunique()

1161

In [42]:
# defining the new DataFrame

good_stores_df = df[df["Store Number"].isin(good_stores)]

In [43]:
good_stores_df.head()

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
0,2015-11-04,3717,SUMNER,50674,9,Bremer,1051100,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,4.50,6.75,12,81.00,9.0,2.38
1,2016-03-02,2614,DAVENPORT,52807,82,Scott,1011100,BLENDED WHISKIES,395,27605,Tin Cup,750,13.75,20.63,2,41.26,1.5,0.40
2,2016-02-11,2106,CEDAR FALLS,50613,7,Black Hawk,1011200,STRAIGHT BOURBON WHISKIES,65,19067,Jim Beam,1000,12.59,18.89,24,453.36,24.0,6.34
3,2016-02-03,2501,AMES,50010,85,Story,1071100,AMERICAN COCKTAILS,395,59154,1800 Ultimate Margarita,1750,9.50,14.25,6,85.50,10.5,2.77
4,2015-08-18,3654,BELMOND,50421,99,Wright,1031080,VODKA 80 PROOF,297,35918,Five O'clock Vodka,1750,7.20,10.80,12,129.60,21.0,5.55

In [44]:
# After removal of partial year stores get to 1161

good_stores_df['Store Number'].nunique()

1161

In [45]:
good_stores_df.shape # taking out the partial year stores - lose 5% of observations - acceptable adjustment

(253937, 18)

In [46]:
df.shape

(266938, 18)

In [47]:
pct_of_total_obs_elim = (1 - (good_stores_df.shape[0]*1.0 / df.shape[0])) * 100
pct_of_total_obs_elim

4.870419348313093

Taking out the partial year stores would result in losing in less than 5% of the total observations -- seems reasonable

In [48]:
df = good_stores_df
df.describe()

,Store Number,County Number,Category,Vendor Number,Item Number,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons)
count,253937.00,253937.00,2.54e+05,253937.00,253937.00,253937.00,253937.00,253937.00,253937.00,253937.00,253937.00,253937.00
mean,3525.04,57.02,1.04e+06,256.33,45884.95,927.53,9.71,14.58,8.43,108.24,7.44,1.97
std,914.30,27.47,4.99e+04,141.33,51461.01,490.01,6.29,9.44,9.16,141.76,8.87,2.34
min,2106.00,1.00,1.01e+06,10.00,168.00,50.00,0.89,1.34,1.00,1.34,0.10,0.03
25%,2597.00,31.00,1.01e+06,115.00,26827.00,750.00,5.51,8.31,2.00,30.02,1.50,0.40
50%,3666.00,61.00,1.03e+06,260.00,38176.00,750.00,8.00,12.30,6.00,69.60,5.25,1.39
75%,4296.00,77.00,1.06e+06,380.00,64676.00,1000.00,11.92,17.88,12.00,134.97,10.50,2.77
max,9010.00,99.00,1.70e+06,978.00,994945.00,4800.00,65.99,98.99,75.00,3429.36,153.00,40.42

## Computing New Columns and Tables

Since we're trying to predict sales and/or profits, we'll want to compute some intermediate data. There are a lot of ways to do this and good use of pandas is crucial. For example, for each transaction we may want to know:
* unit margin = retail cost minus bottle cost
* gross margin = gross margin * bottles sold
* price per bottle
* price per liter

We'll need to make a new dataframe that indexes quantities by store:
* sales per store for all of 2015
* sales per store for Q1 2015
* sales per store for Q1 2016
* total volumes sold
* mean transaction revenue, gross margin, price per bottle, price per liter, etc.
* average sales per day
* number of days open (count of sales per store) - this is wrong because there would be more than 365!!!

Make sure to retain other variables that we'll want to use to build our models, such as zip code, county number, city, etc. We recommend that you spend some time thinking about the model you may want to fit and computing enough of the suggested quantities to give you a few options.

Bonus tasks:
* Restrict your attention to stores that were open for all of 2015 and Q1 2016. Stores that opened or closed in 2015 will introduce outliers into your data.
* For each transaction we have the item category. You may be able to determine the store type (primarily wine, liquor, all types of alcohol, etc.) by the most common transaction category for each store. This could be a useful categorical variable for modelling.

### Transaction Level Metrics

##### Calculating Unit Margin

In [49]:
df["Transaction Unit Margin"] = (df["State Bottle Retail"] - df["State Bottle Cost"])

##### Calculating Gross Margin - Perhaps Name this Gross Profits

In [50]:
df["Gross Profit (Dollars)"] = (df["State Bottle Retail"] - df["State Bottle Cost"]) * df["Bottles Sold"]

##### Calculating Gross Margin %

In [51]:
df["Transaction Unit Margin%"] = (1 - (df["State Bottle Cost"]/df["State Bottle Retail"]))*100

##### Revenue per Liter

In [52]:
df["Transaction Revenue per Liter"] = df["Sale (Dollars)"] / df["Volume Sold (Liters)"]

##### Gross Margin per Liter

In [53]:
df["Transaction Gross Margin per Liter"] = ((df["State Bottle Retail"] - df["State Bottle Cost"]) 
                                * df["Bottles Sold"]) / df["Volume Sold (Liters)"]

Checking our DataFrame after new column additions

In [54]:
df.head(2)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),State Bottle Cost,State Bottle Retail,Bottles Sold,Sale (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Transaction Unit Margin,Gross Profit (Dollars),Transaction Unit Margin%,Transaction Revenue per Liter,Transaction Gross Margin per Liter
0,2015-11-04,3717,SUMNER,50674,9,Bremer,1051100,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,4.50,6.75,12,81.00,9.0,2.38,2.25,27.00,33.33,9.00,3.00
1,2016-03-02,2614,DAVENPORT,52807,82,Scott,1011100,BLENDED WHISKIES,395,27605,Tin Cup,750,13.75,20.63,2,41.26,1.5,0.40,6.88,13.76,33.35,27.51,9.17

In [55]:
df = df.rename(columns={'State Bottle Cost': 'Cost per Bottle',
                        'State Bottle Retail': 'Retail Price per Bottle',
                        'Sale (Dollars)': 'Revenues (Dollars)'
                       })

df.head(2)

,Date,Store Number,City,Zip Code,County Number,County,Category,Category Name,Vendor Number,Item Number,Item Description,Bottle Volume (ml),Cost per Bottle,Retail Price per Bottle,Bottles Sold,Revenues (Dollars),Volume Sold (Liters),Volume Sold (Gallons),Transaction Unit Margin,Gross Profit (Dollars),Transaction Unit Margin%,Transaction Revenue per Liter,Transaction Gross Margin per Liter
0,2015-11-04,3717,SUMNER,50674,9,Bremer,1051100,APRICOT BRANDIES,55,54436,Mr. Boston Apricot Brandy,750,4.50,6.75,12,81.00,9.0,2.38,2.25,27.00,33.33,9.00,3.00
1,2016-03-02,2614,DAVENPORT,52807,82,Scott,1011100,BLENDED WHISKIES,395,27605,Tin Cup,750,13.75,20.63,2,41.26,1.5,0.40,6.88,13.76,33.35,27.51,9.17

### Calculating per Store Metrics for 2015

Step 1 - Filtering by start and end dates (January 1, 2015 and December 31, 2015, respectively)

In [56]:
df.sort_values(by=["Store Number", "Date"], inplace=True)

start_date = pd.Timestamp("20150101")
end_date = pd.Timestamp("20151231")

mask_2015 = (df['Date'] >= start_date) & (df['Date'] <= end_date)
stores_2015_df = df[mask_2015]

In [57]:
stores_2015_df.shape

(206344, 23)

In [58]:
# Calculating total Iowa liquor sales 2015
iowa_liquor_sales_2015 = stores_2015_df['Revenues (Dollars)'].sum()
iowa_liquor_sales_2015

22505492.67000281

In [59]:
# Calculating total Iowa gross margin 2015
iowa_liquor_gross_margin_2015 = stores_2015_df['Gross Profit (Dollars)'].sum()
iowa_liquor_gross_margin_2015

7520830.2599976845

##### Calculating Total Iowa Sales for 1Q'2015

Goal of this code block is to generate a dataframe that has info for 1Q'15, which we will then use to combine with data from question is to see if there is any seasonality in sales.  Our original data set runs from January 1, 2015 to March 31, 2016.  If sales were significantly skewed higher or lower in 1Q, by including the whole data set we would be skewing our numbers as we would have two 1Q's (2015 and 2016).

In [60]:
df.sort_values(by=["Store Number", "Date"], inplace=True)

start_date = pd.Timestamp("20150101")
end_date = pd.Timestamp("20150331")

mask_1Q15 = (df['Date'] >= start_date) & (df['Date'] <= end_date)
stores_1Q15_df = df[mask_1Q15]

In [61]:
stores_1Q15_df.shape

(47432, 23)

In [62]:
# Calculating total Iowa liquor sales 1Q15
iowa_liquor_sales_1Q15 = stores_1Q15_df['Revenues (Dollars)'].sum()
iowa_liquor_sales_1Q15

5014523.259999812

In [63]:
iowa_liquor_sales_2015/4*1.0

5626373.167500703

In [64]:
iowa_liquor_sales_1Q15/iowa_liquor_sales_2015 # expect this to be close to 0.25 if no seasonality

0.22281330755685186

In [65]:
# Calculating total Iowa gross margin 2015
iowa_liquor_gross_margin_1Q15 = stores_1Q15_df['Gross Profit (Dollars)'].sum()
iowa_liquor_gross_margin_1Q15

1675757.2200000596

In [66]:
iowa_liquor_gross_margin_2015/4*1.0

1880207.5649994211

In [67]:
iowa_liquor_gross_margin_1Q15/iowa_liquor_gross_margin_2015

0.22281545548410975

##### Conclusion: no real seasonality in sales and gross margin

##### Looking at Q12016 Sales - Was There Any Growth Year Over Year?

In [68]:
df.sort_values(by=["Store Number", "Date"], inplace=True)

start_date = pd.Timestamp("20160101")
end_date = pd.Timestamp("20160331")

mask_1Q16 = (df['Date'] >= start_date) & (df['Date'] <= end_date)
stores_1Q16_df = df[mask_1Q16]

In [69]:
stores_1Q16_df.shape

(47593, 23)

In [70]:
# Calculating total Iowa liquor sales 1Q16
iowa_liquor_sales_1Q16 = stores_1Q16_df['Revenues (Dollars)'].sum()
iowa_liquor_sales_1Q16

4979727.799999831

In [71]:
((iowa_liquor_sales_1Q16/iowa_liquor_sales_1Q15)-1)*100

-0.6938936803332685

In [72]:
# System wide year-over-year sales growth was flat

### Back to Calculating Sales per Store for 2015

Step 2 - Group by Store Number

In [73]:
stores_2015_df = stores_2015_df.groupby(by="Store Number", as_index=False)

### Step 3 - Compute sums, means for key metrics and collapse the column indicies

In [74]:
# When you see np.mean calculated for a column -- interpret it as average per store

stores_2015_df = stores_2015_df.agg({"Bottles Sold": [np.sum, np.mean, 'max', 'min'], 
                                     "Volume Sold (Liters)": [np.sum, np.mean],
        
                                     "Revenues (Dollars)": [np.sum, np.mean, 'count'],
                                     "Gross Profit (Dollars)": [np.sum, np.mean],
                                     
                                     "Retail Price per Bottle": np.mean,
                                     "Cost per Bottle": np.mean,
                                     "Transaction Unit Margin": np.mean,
                                     "Transaction Unit Margin%": np.mean,
                                     
                                     "Transaction Revenue per Liter": np.mean,
                                     "Transaction Gross Margin per Liter": np.mean,
                                     
                                     "Zip Code": lambda x: x.iloc[0], # just extract once, should be the same
                                     "City": lambda x: x.iloc[0],
                                     "County Number": lambda x: x.iloc[0],
                                     "County": lambda x: x.iloc[0],
                                     "Category": 'nunique',
                                     "Category Name": lambda x:x.value_counts().index[0], # returns the most common
                                     "Vendor Number": 'nunique',
                                     "Item Number": 'nunique',
                                     "Item Description": lambda x:x.value_counts().index[0],
                                   
                                     "Date": ['nunique', 'count'], 
                                     # confirming the number of transactions per store in time period
                                     # count should match count for Sale (Dollars), but 'nunique' = number of days open
                                   
                                    })

stores_2015_df.columns = [' '.join(col).strip() for col in stores_2015_df.columns.values]

stores_2015_df.head(2)

,Store Number,Category nunique,Cost per Bottle mean,Gross Profit (Dollars) sum,Gross Profit (Dollars) mean,Transaction Unit Margin mean,Transaction Gross Margin per Liter mean,City <lambda>,Vendor Number nunique,Transaction Unit Margin% mean,Revenues (Dollars) sum,Revenues (Dollars) mean,Revenues (Dollars) count,Zip Code <lambda>,Retail Price per Bottle mean,County <lambda>,County Number <lambda>,Bottles Sold sum,Bottles Sold mean,Bottles Sold max,Bottles Sold min,Category Name <lambda>,Volume Sold (Liters) sum,Volume Sold (Liters) mean,Date nunique,Date count,Item Description <lambda>,Item Number nunique,Transaction Revenue per Liter mean
0,2106,48,10.18,41723.72,81.65,5.10,5.89,CEDAR FALLS,32,33.40,125057.54,244.73,511,50613,15.29,Black Hawk,7,8625,16.88,72,1,CANADIAN WHISKIES,8020.35,15.70,52,511,Black Velvet,244,17.63
1,2113,36,10.87,3109.04,21.15,5.45,6.17,GOWRIE,23,33.39,9310.22,63.33,147,50543,16.32,Webster,94,671,4.56,24,1,CANADIAN WHISKIES,659.85,4.49,47,147,Patron Tequila Silver,94,18.51

##### Renaming column names

In [75]:
stores_2015_df.columns = stores_2015_df.columns.str.replace(' <lambda>', '')

In [76]:
stores_2015_df.drop(['Date count'], axis=1, inplace=True)

In [77]:
stores_2015_df.head(2)

,Store Number,Category nunique,Cost per Bottle mean,Gross Profit (Dollars) sum,Gross Profit (Dollars) mean,Transaction Unit Margin mean,Transaction Gross Margin per Liter mean,City,Vendor Number nunique,Transaction Unit Margin% mean,Revenues (Dollars) sum,Revenues (Dollars) mean,Revenues (Dollars) count,Zip Code,Retail Price per Bottle mean,County,County Number,Bottles Sold sum,Bottles Sold mean,Bottles Sold max,Bottles Sold min,Category Name,Volume Sold (Liters) sum,Volume Sold (Liters) mean,Date nunique,Item Description,Item Number nunique,Transaction Revenue per Liter mean
0,2106,48,10.18,41723.72,81.65,5.10,5.89,CEDAR FALLS,32,33.40,125057.54,244.73,511,50613,15.29,Black Hawk,7,8625,16.88,72,1,CANADIAN WHISKIES,8020.35,15.70,52,Black Velvet,244,17.63
1,2113,36,10.87,3109.04,21.15,5.45,6.17,GOWRIE,23,33.39,9310.22,63.33,147,50543,16.32,Webster,94,671,4.56,24,1,CANADIAN WHISKIES,659.85,4.49,47,Patron Tequila Silver,94,18.51

In [78]:
stores_2015_df.rename(columns={'Category nunique': 'Number of Liquor Categories Offered',
                               'Category Name': 'Best Selling Category',
                               'Cost per Bottle mean': 'Average Transaction Cost per Bottle',
                               'Gross Profit (Dollars) sum': 'Store Gross Profit (Dollars)',
                               'Gross Profit (Dollars) mean': 'Average Transaction Gross Profit',
                               'Transaction Unit Margin mean': 'Average Transaction Unit Margin',
                               'Vendor Number nunique': 'Number of Suppliers',
                               'Transaction Unit Margin% mean': 'Average Transaction Unit Margin%',
                               'Revenues (Dollars) sum': 'Store Revenues (Dollars)',
                               'Revenues (Dollars) mean': 'Average Revenues per Transaction',
                               'Revenues (Dollars) count': 'Number of Transactions in Period',
                               'Retail Price per Bottle mean': 'Average Retail (Transaction) Price per Bottle',
                               'Bottles Sold sum': 'Store Bottles Sold',
                               'Bottles Sold mean': 'Average Bottles Sold per Transaction',
                               'Bottles Sold max': 'Max Bottles Sold per Transaction',
                               'Bottles Sold min': 'Min Bottles Sold per Transaction',
                               'Volume Sold (Liters) sum': 'Store Volume (liters)',
                               'Volume Sold (Liters) mean': 'Average Liters Sold per Transaction',
                               'Date nunique': 'Store Operating Days',
                               'Item Number nunique': 'Number of Products Offered',
                               'Item Description': 'Best Selling Item',
                               'Transaction Revenue per Liter mean': 'Average Transaction Revenue per Liter'
                              }, inplace=True)

stores_2015_df.head(2)

,Store Number,Number of Liquor Categories Offered,Average Transaction Cost per Bottle,Store Gross Profit (Dollars),Average Transaction Gross Profit,Average Transaction Unit Margin,Transaction Gross Margin per Liter mean,City,Number of Suppliers,Average Transaction Unit Margin%,Store Revenues (Dollars),Average Revenues per Transaction,Number of Transactions in Period,Zip Code,Average Retail (Transaction) Price per Bottle,County,County Number,Store Bottles Sold,Average Bottles Sold per Transaction,Max Bottles Sold per Transaction,Min Bottles Sold per Transaction,Best Selling Category,Store Volume (liters),Average Liters Sold per Transaction,Store Operating Days,Best Selling Item,Number of Products Offered,Average Transaction Revenue per Liter
0,2106,48,10.18,41723.72,81.65,5.10,5.89,CEDAR FALLS,32,33.40,125057.54,244.73,511,50613,15.29,Black Hawk,7,8625,16.88,72,1,CANADIAN WHISKIES,8020.35,15.70,52,Black Velvet,244,17.63
1,2113,36,10.87,3109.04,21.15,5.45,6.17,GOWRIE,23,33.39,9310.22,63.33,147,50543,16.32,Webster,94,671,4.56,24,1,CANADIAN WHISKIES,659.85,4.49,47,Patron Tequila Silver,94,18.51

### Now we can create store level metrics

In [79]:
stores_2015_df['Store Bottles Sold per Day'] = (stores_2015_df['Store Bottles Sold'] / 
                                                stores_2015_df['Store Operating Days'])

In [80]:
stores_2015_df['Store Liters Sold per Day'] = (stores_2015_df['Store Volume (liters)'] / 
                                                stores_2015_df['Store Operating Days'])

In [81]:
stores_2015_df['Store Revenues per Day'] = (stores_2015_df['Store Revenues (Dollars)'] / 
                                            stores_2015_df['Store Operating Days'])

In [82]:
stores_2015_df['Store Revenues per Bottle'] = (stores_2015_df['Store Revenues (Dollars)'] / 
                                               stores_2015_df['Store Bottles Sold'])

In [83]:
stores_2015_df['Store Revenues per Liter'] = (stores_2015_df['Store Revenues (Dollars)'] / 
                                               stores_2015_df['Store Volume (liters)'])

In [84]:
stores_2015_df['Store Gross Profits per Day'] = (stores_2015_df['Store Gross Profit (Dollars)'] / 
                                                 stores_2015_df['Store Operating Days'])

In [85]:
stores_2015_df['Store Gross Profit Margin%'] = (stores_2015_df['Store Gross Profit (Dollars)'] / 
                                                stores_2015_df['Store Revenues (Dollars)']) * 100

In [86]:
stores_2015_df['Store Unit Margin'] = (stores_2015_df['Store Gross Profit (Dollars)'] / 
                                       stores_2015_df['Store Bottles Sold'])

In [87]:
stores_2015_df['Store Gross Profit per Liter'] = (stores_2015_df['Store Gross Profit (Dollars)'] / 
                                                  stores_2015_df['Store Volume (liters)'])

In [88]:
stores_2015_df.head(2)

,Store Number,Number of Liquor Categories Offered,Average Transaction Cost per Bottle,Store Gross Profit (Dollars),Average Transaction Gross Profit,Average Transaction Unit Margin,Transaction Gross Margin per Liter mean,City,Number of Suppliers,Average Transaction Unit Margin%,Store Revenues (Dollars),Average Revenues per Transaction,Number of Transactions in Period,Zip Code,Average Retail (Transaction) Price per Bottle,County,County Number,Store Bottles Sold,Average Bottles Sold per Transaction,Max Bottles Sold per Transaction,Min Bottles Sold per Transaction,Best Selling Category,Store Volume (liters),Average Liters Sold per Transaction,Store Operating Days,Best Selling Item,Number of Products Offered,Average Transaction Revenue per Liter,Store Bottles Sold per Day,Store Liters Sold per Day,Store Revenues per Day,Store Revenues per Bottle,Store Revenues per Liter,Store Gross Profits per Day,Store Gross Profit Margin%,Store Unit Margin,Store Gross Profit per Liter
0,2106,48,10.18,41723.72,81.65,5.10,5.89,CEDAR FALLS,32,33.40,125057.54,244.73,511,50613,15.29,Black Hawk,7,8625,16.88,72,1,CANADIAN WHISKIES,8020.35,15.70,52,Black Velvet,244,17.63,165.87,154.24,2404.95,14.50,15.59,802.38,33.36,4.84,5.20
1,2113,36,10.87,3109.04,21.15,5.45,6.17,GOWRIE,23,33.39,9310.22,63.33,147,50543,16.32,Webster,94,671,4.56,24,1,CANADIAN WHISKIES,659.85,4.49,47,Patron Tequila Silver,94,18.51,14.28,14.04,198.09,13.88,14.11,66.15,33.39,4.63,4.71

### Looking at Combining ZIP Code Data - Little Differentiation with City - same number - slightly different grouping, County may be a blunt instrument

In [89]:
zip_stats_df = stores_2015_df.groupby(by='Zip Code', 
                                      as_index=False).agg({'Store Number': 'count',
                                                           'Store Revenues (Dollars)': np.sum,
                                                           'Store Gross Profit (Dollars)': np.sum,
                                                           'Store Bottles Sold': np.sum,
                                                           'Store Volume (liters)': np.sum
                                                          })

zip_stats_df.head()

,Zip Code,Store Bottles Sold,Store Gross Profit (Dollars),Store Number,Store Revenues (Dollars),Store Volume (liters)
0,50002,498,1663.48,2,4958.04,335.85
1,50003,2234,8521.71,3,25459.94,1924.52
2,50006,508,3017.89,1,9031.81,629.24
3,50009,16470,72849.03,9,217957.37,14844.15
4,50010,43731,202785.51,20,606826.07,41321.12

In [90]:
zip_stats_df.tail()

,Zip Code,Store Bottles Sold,Store Gross Profit (Dollars),Store Number,Store Revenues (Dollars),Store Volume (liters)
371,52804,27467,102179.84,10,305962.90,20689.05
372,52806,14574,54463.01,8,162914.36,11592.10
373,52807,28498,133677.17,9,399989.92,25369.10
374,56201,276,1362.78,1,4086.72,243.00
375,712-2,1020,5002.98,1,14990.99,1020.65

In [91]:
zip_stats_df = zip_stats_df.rename(columns={'Store Bottles Sold': 'Zip Bottles Sold',
                                            'Store Gross Profit (Dollars)': 'Zip Gross Profit (Dollars)',
                                            'Store Number': 'Number of Stores by Zip',
                                            'Store Revenues (Dollars)': 'Zip Revenues (Dollars)',
                                            'Store Volume (liters)': 'Zip Volume (liters)'
                                           })

zip_stats_df.head(2)

,Zip Code,Zip Bottles Sold,Zip Gross Profit (Dollars),Number of Stores by Zip,Zip Revenues (Dollars),Zip Volume (liters)
0,50002,498,1663.48,2,4958.04,335.85
1,50003,2234,8521.71,3,25459.94,1924.52

### Now we can create Zip Code level metrics

Potential Proxies for Competiton:
- Number of Stores by Zip 
- Zip Revenues per Store
- Zip Gross Profit per Store
- Zip Gross Profit Margin% (lower competition, higher relative pricing power)

Potential Proxy for Zip Code Income Characteristics:

Zip Revenue per Bottle or Liter -- higher end products will have higher unit prices

In [92]:
zip_stats_df['Zip Revenues per Store'] = (zip_stats_df['Zip Revenues (Dollars)'] / 
                                          zip_stats_df['Number of Stores by Zip'])

In [93]:
zip_stats_df['Zip Gross Profit per Store'] = (zip_stats_df['Zip Gross Profit (Dollars)'] / 
                                              zip_stats_df['Number of Stores by Zip'])

In [94]:
zip_stats_df['Zip Gross Profit Margin%'] = (zip_stats_df['Zip Gross Profit (Dollars)'] / 
                                            zip_stats_df['Zip Revenues (Dollars)']) * 100

In [95]:
zip_stats_df['Zip Revenue per Bottle'] = (zip_stats_df['Zip Revenues (Dollars)'] / 
                                          zip_stats_df['Zip Bottles Sold'])

In [96]:
zip_stats_df['Zip Revenue per Liter'] = (zip_stats_df['Zip Revenues (Dollars)'] / 
                                         zip_stats_df['Zip Volume (liters)'])

In [97]:
zip_stats_df['Zip Gross Profit per Bottle'] = (zip_stats_df['Zip Gross Profit (Dollars)'] / 
                                               zip_stats_df['Zip Bottles Sold'])

In [98]:
zip_stats_df['Zip Gross Profit per Liter'] = (zip_stats_df['Zip Gross Profit (Dollars)'] / 
                                              zip_stats_df['Zip Volume (liters)'])

In [99]:
zip_stats_df.head()

,Zip Code,Zip Bottles Sold,Zip Gross Profit (Dollars),Number of Stores by Zip,Zip Revenues (Dollars),Zip Volume (liters),Zip Revenues per Store,Zip Gross Profit per Store,Zip Gross Profit Margin%,Zip Revenue per Bottle,Zip Revenue per Liter,Zip Gross Profit per Bottle,Zip Gross Profit per Liter
0,50002,498,1663.48,2,4958.04,335.85,2479.02,831.74,33.55,9.96,14.76,3.34,4.95
1,50003,2234,8521.71,3,25459.94,1924.52,8486.65,2840.57,33.47,11.40,13.23,3.81,4.43
2,50006,508,3017.89,1,9031.81,629.24,9031.81,3017.89,33.41,17.78,14.35,5.94,4.80
3,50009,16470,72849.03,9,217957.37,14844.15,24217.49,8094.34,33.42,13.23,14.68,4.42,4.91
4,50010,43731,202785.51,20,606826.07,41321.12,30341.30,10139.28,33.42,13.88,14.69,4.64,4.91

In [100]:
stores_2015_df['Store Number'].nunique()

1161

In [101]:
zip_stats_df['Number of Stores by Zip'].sum() # confirm match with above to ensure groupby is working

1161

In [116]:
zip_stats_df['Zip Revenues (Dollars)'].sum() # Total Iowa Liquor Revenues in 2015

22505492.669999976

##### Merging Store Level Data and Zip Code (Market) Data

In [102]:
store_zip_df = stores_2015_df.merge(zip_stats_df, left_on='Zip Code', right_on='Zip Code', how='inner')

store_zip_df.head()

,Store Number,Number of Liquor Categories Offered,Average Transaction Cost per Bottle,Store Gross Profit (Dollars),Average Transaction Gross Profit,Average Transaction Unit Margin,Transaction Gross Margin per Liter mean,City,Number of Suppliers,Average Transaction Unit Margin%,Store Revenues (Dollars),Average Revenues per Transaction,Number of Transactions in Period,Zip Code,Average Retail (Transaction) Price per Bottle,County,County Number,Store Bottles Sold,Average Bottles Sold per Transaction,Max Bottles Sold per Transaction,Min Bottles Sold per Transaction,Best Selling Category,Store Volume (liters),Average Liters Sold per Transaction,Store Operating Days,Best Selling Item,Number of Products Offered,Average Transaction Revenue per Liter,Store Bottles Sold per Day,Store Liters Sold per Day,Store Revenues per Day,Store Revenues per Bottle,Store Revenues per Liter,Store Gross Profits per Day,Store Gross Profit Margin%,Store Unit Margin,Store Gross Profit per Liter,Zip Bottles Sold,Zip Gross Profit (Dollars),Number of Stores by Zip,Zip Revenues (Dollars),Zip Volume (liters),Zip Revenues per Store,Zip Gross Profit per Store,Zip Gross Profit Margin%,Zip Revenue per Bottle,Zip Revenue per Liter,Zip Gross Profit per Bottle,Zip Gross Profit per Liter
0,2106,48,10.18,41723.72,81.65,5.10,5.89,CEDAR FALLS,32,33.40,125057.54,244.73,511,50613,15.29,Black Hawk,7,8625,16.88,72,1,CANADIAN WHISKIES,8020.35,15.70,52,Black Velvet,244,17.63,165.87,154.24,2404.95,14.50,15.59,802.38,33.36,4.84,5.20,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
1,2572,59,9.96,27681.85,21.34,5.00,6.28,CEDAR FALLS,51,33.47,82799.91,63.84,1297,50613,14.96,Black Hawk,7,5817,4.48,60,1,VODKA FLAVORED,5303.74,4.09,52,Five O'clock Vodka,736,18.79,111.87,102.00,1592.31,14.23,15.61,532.34,33.43,4.76,5.22,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
2,2835,26,10.71,3941.47,34.27,5.39,4.84,CEDAR FALLS,21,33.52,11751.32,102.19,115,50613,16.11,Black Hawk,7,790,6.87,30,1,VODKA 80 PROOF,991.50,8.62,37,Ten High,73,14.46,21.35,26.80,317.60,14.88,11.85,106.53,33.54,4.99,3.98,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
3,3769,31,9.90,17983.56,57.27,4.98,4.51,CEDAR FALLS,24,33.47,53725.80,171.10,314,50613,14.87,Black Hawk,7,3852,12.27,66,6,VODKA 80 PROOF,4437.00,14.13,52,Admiral Nelson Spiced Rum,139,13.49,74.08,85.33,1033.19,13.95,12.11,345.84,33.47,4.67,4.05,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
4,3995,36,10.88,13330.86,69.43,5.45,6.10,CEDAR FALLS,24,33.37,39946.95,208.06,192,50613,16.32,Black Hawk,7,2822,14.70,72,1,FLAVORED RUM,2602.00,13.55,51,Juarez Tequila Gold,98,18.30,55.33,51.02,783.27,14.16,15.35,261.39,33.37,4.72,5.12,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9

In [103]:
store_zip_df.shape

(1161, 49)

In [104]:
store_zip_df.describe()

,Store Number,Number of Liquor Categories Offered,Average Transaction Cost per Bottle,Store Gross Profit (Dollars),Average Transaction Gross Profit,Average Transaction Unit Margin,Transaction Gross Margin per Liter mean,Number of Suppliers,Average Transaction Unit Margin%,Store Revenues (Dollars),Average Revenues per Transaction,Number of Transactions in Period,Average Retail (Transaction) Price per Bottle,County Number,Store Bottles Sold,Average Bottles Sold per Transaction,Max Bottles Sold per Transaction,Min Bottles Sold per Transaction,Store Volume (liters),Average Liters Sold per Transaction,Store Operating Days,Number of Products Offered,Average Transaction Revenue per Liter,Store Bottles Sold per Day,Store Liters Sold per Day,Store Revenues per Day,Store Revenues per Bottle,Store Revenues per Liter,Store Gross Profits per Day,Store Gross Profit Margin%,Store Unit Margin,Store Gross Profit per Liter,Zip Bottles Sold,Zip Gross Profit (Dollars),Number of Stores by Zip,Zip Revenues (Dollars),Zip Volume (liters),Zip Revenues per Store,Zip Gross Profit per Store,Zip Gross Profit Margin%,Zip Revenue per Bottle,Zip Revenue per Liter,Zip Gross Profit per Bottle,Zip Gross Profit per Liter
count,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00,1161.00
mean,4147.58,25.17,9.07,6477.89,36.74,4.55,5.67,19.73,33.43,19384.58,109.92,177.73,13.62,55.93,1505.86,9.53,41.22,2.15,1330.37,7.89,35.37,107.59,16.98,34.91,29.98,428.78,11.85,14.06,143.31,33.43,3.96,4.70,13424.78,57540.40,7.34,172198.50,11585.00,19384.58,6477.89,33.43,12.55,14.06,4.19,4.70
std,814.66,13.17,1.88,11576.09,19.39,0.94,1.21,9.36,0.08,34667.84,58.06,233.12,2.82,28.13,2246.29,4.16,18.93,2.07,2102.98,3.50,18.20,127.42,3.64,30.51,29.45,464.04,3.24,3.25,154.99,0.09,1.08,1.08,13726.61,60173.77,6.10,180106.22,11653.47,15105.61,5043.02,0.06,1.87,1.76,0.62,0.59
min,2106.00,2.00,2.97,176.16,7.96,1.49,3.18,1.00,33.21,528.24,23.83,4.00,4.46,1.00,36.00,2.17,10.00,1.00,36.00,1.70,2.00,4.00,9.50,6.55,3.92,64.68,3.41,7.87,21.64,33.34,1.14,2.65,48.00,191.64,1.00,573.51,48.15,573.51,191.64,33.34,4.76,7.87,1.59,2.65
25%,3783.00,15.00,7.85,1323.02,25.10,3.94,4.96,13.00,33.38,3954.84,75.06,40.00,11.79,31.00,374.00,6.54,24.00,1.00,291.34,5.53,19.00,29.00,14.82,17.15,14.34,188.73,9.59,12.14,62.99,33.37,3.20,4.06,1806.00,8060.47,2.00,24135.73,1797.38,9311.36,3113.73,33.40,11.51,13.12,3.85,4.38
50%,4364.00,23.00,9.05,2771.65,34.03,4.54,5.52,18.00,33.42,8266.29,101.77,96.00,13.60,57.00,754.00,9.10,48.00,1.00,625.35,7.31,39.00,62.00,16.54,24.29,19.47,263.54,12.02,13.64,88.09,33.41,4.02,4.56,7980.00,32990.08,5.00,98706.97,7129.58,18331.23,6124.23,33.42,12.79,14.08,4.27,4.70
75%,4726.00,33.00,10.12,6602.37,44.79,5.08,6.21,24.00,33.46,19787.80,133.98,195.00,15.21,78.00,1710.00,11.62,60.00,2.00,1399.49,9.75,50.00,121.00,18.59,39.06,30.68,430.68,14.05,15.22,143.84,33.46,4.70,5.09,21419.00,95069.00,11.00,284422.66,18599.92,25084.66,8383.04,33.44,13.63,14.80,4.56,4.95
max,9010.00,62.00,19.04,176936.11,262.40,9.54,27.32,58.00,34.04,530136.48,787.05,1865.00,28.58,99.00,31872.00,34.15,75.00,12.00,29233.99,33.73,198.00,736.00,81.92,246.75,230.69,4167.90,31.05,68.01,1390.78,34.22,10.35,22.67,53228.00,238724.43,24.00,714507.89,44061.55,169228.88,56480.37,34.11,21.48,22.85,7.16,7.62

#### What Differentiates Successful Stores from Average Stores?

Our task is to investigate the Iowa State Liquor dataset to recommend locations for our client's store expansion program.  Now that we have loaded, cleaned and parsed through the data -- it is time to synthesize some insights that will form the basis of our model.

From the data we have aquired, the next logical step is to determine what are the common characteristics of 'successful' stores.

Define 'successful' stores as being in the top quartile in sales per day ~ $430

In [105]:
topquartile_df = store_zip_df[store_zip_df['Store Revenues per Day'] >= 430]

topquartile_df.head()

,Store Number,Number of Liquor Categories Offered,Average Transaction Cost per Bottle,Store Gross Profit (Dollars),Average Transaction Gross Profit,Average Transaction Unit Margin,Transaction Gross Margin per Liter mean,City,Number of Suppliers,Average Transaction Unit Margin%,Store Revenues (Dollars),Average Revenues per Transaction,Number of Transactions in Period,Zip Code,Average Retail (Transaction) Price per Bottle,County,County Number,Store Bottles Sold,Average Bottles Sold per Transaction,Max Bottles Sold per Transaction,Min Bottles Sold per Transaction,Best Selling Category,Store Volume (liters),Average Liters Sold per Transaction,Store Operating Days,Best Selling Item,Number of Products Offered,Average Transaction Revenue per Liter,Store Bottles Sold per Day,Store Liters Sold per Day,Store Revenues per Day,Store Revenues per Bottle,Store Revenues per Liter,Store Gross Profits per Day,Store Gross Profit Margin%,Store Unit Margin,Store Gross Profit per Liter,Zip Bottles Sold,Zip Gross Profit (Dollars),Number of Stores by Zip,Zip Revenues (Dollars),Zip Volume (liters),Zip Revenues per Store,Zip Gross Profit per Store,Zip Gross Profit Margin%,Zip Revenue per Bottle,Zip Revenue per Liter,Zip Gross Profit per Bottle,Zip Gross Profit per Liter
0,2106,48,10.18,41723.72,81.65,5.10,5.89,CEDAR FALLS,32,33.40,125057.54,244.73,511,50613,15.29,Black Hawk,7,8625,16.88,72,1,CANADIAN WHISKIES,8020.35,15.70,52,Black Velvet,244,17.63,165.87,154.24,2404.95,14.50,15.59,802.38,33.36,4.84,5.20,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
1,2572,59,9.96,27681.85,21.34,5.00,6.28,CEDAR FALLS,51,33.47,82799.91,63.84,1297,50613,14.96,Black Hawk,7,5817,4.48,60,1,VODKA FLAVORED,5303.74,4.09,52,Five O'clock Vodka,736,18.79,111.87,102.00,1592.31,14.23,15.61,532.34,33.43,4.76,5.22,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
3,3769,31,9.90,17983.56,57.27,4.98,4.51,CEDAR FALLS,24,33.47,53725.80,171.10,314,50613,14.87,Black Hawk,7,3852,12.27,66,6,VODKA 80 PROOF,4437.00,14.13,52,Admiral Nelson Spiced Rum,139,13.49,74.08,85.33,1033.19,13.95,12.11,345.84,33.47,4.67,4.05,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
4,3995,36,10.88,13330.86,69.43,5.45,6.10,CEDAR FALLS,24,33.37,39946.95,208.06,192,50613,16.32,Black Hawk,7,2822,14.70,72,1,FLAVORED RUM,2602.00,13.55,51,Juarez Tequila Gold,98,18.30,55.33,51.02,783.27,14.16,15.35,261.39,33.37,4.72,5.12,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9
5,4119,19,11.56,2390.58,61.30,5.78,6.53,CEDAR FALLS,14,33.34,7169.42,183.83,39,50613,17.35,Black Hawk,7,424,10.87,24,4,VODKA 80 PROOF,403.00,10.33,15,Hawkeye Vodka,32,19.59,28.27,26.87,477.96,16.91,17.79,159.37,33.34,5.64,5.93,34152,152362.59,16,455814.14,31093.08,28488.38,9522.66,33.43,13.35,14.66,4.46,4.9

In [109]:
topquartile_df['Zip Code'].nunique()

132

In [113]:
topquartile_df['Zip Revenues (Dollars)'].unique().sum()

20065141.859999992

In [114]:
store_zip_df['Zip Revenues (Dollars)'].unique().sum()

22505492.669999994

### Groupbys and Pivot Tables

In [106]:
# old_names = ['$a', '$b', '$c', '$d', '$e'] 
# new_names = ['a', 'b', 'c', 'd', 'e']
# df.rename(columns=dict(zip(old_names, new_names)), inplace=True)

In [107]:
test1_df.columns

NameError: name 'test1_df' is not defined

In [ ]:
test1_df.rename(columns=lambda x: x.lstrip(), inplace=True)
test1_df.head(2)

In [ ]:
test1_df.columns

In [ ]:
test1_df.columns = test1_df.columns.str.replace(' <lambda>', '')
test1_df.columns

In [ ]:
test1_df.head(2)

In [ ]:
test1_df.head(2)

In [ ]:
test1_df.columns

In [ ]:
pd.set_option("display.max_rows",2000)

In [ ]:
test1_df

### Groupby and Pivot Tables

In [ ]:
# Need to clean up column names

In [ ]:
zip_sum1_df = test1_df.groupby(by='Zip_Code', 
                               as_index=False).agg({'Volume Sold (Liters) sum': np.sum, #zip vols
                                                    'Volume Sold (Liters) mean': np.mean, #avg store vol
                                                    'Bottles Sold sum': np.sum, #total bottles for zip
                                                    'Bottles Sold mean': np.mean, #bottles/store
        
                                                    'Sale (Dollars) sum': [np.sum, np.mean], #gross sales for zip
                                                    "Total Sales by Zip": lambda x: x.iloc[0],
                                                    'Sale (Dollars) mean': np.mean, #sales per store
                                                    'State Bottle Retail mean': np.mean, #avg sales price
                                                    'Revenue_per_Liter mean': np.mean, #avg rev per liter
                                                                   
                                                    'Gross_Margin sum': np.sum, #Total Gross Margin $s in zip
                                                    'Gross_Margin mean': np.mean, #Average GM per store
                                                    'Gross_Margin_per_Liter mean': np.mean, #Avg GM per liter
                                                    'Unit_Margin mean': np.mean, #Average Unit Margin (bottle)
                                                    
                                                    "Number of Stores by Zip": lambda x: x.iloc[0],
                                                    "Store Number": 'count', # confirms grouby and merge
                                                    "Total Market Size per Store": lambda x: x.iloc[0]
                                                    })

zip_sum1_df

In [ ]:
# Revenue_per_Liter mean mean - get rid off -- should be equal to total revs/total liters
# State Bottle Retail mean mean -- should be equal to total revs/total bottles
# Volume Sold (Liters) mean mean - should be volume by store - total liters/# stores
# Gross_Margin_per_Liter mean mean -- should be gross margin per liter by store
# Unit_Margin mean mean -- 
# Basically need to get rid of all the mean means

# need to recalc the unit margins for the zip as a whole not as an average of the stores in the zip

In [ ]:
zip_economics = zip_sum1_df.describe()
zip_economics

In [ ]:
# Renaming the column headings
# econ_data_df.columns = ['Zip Code', 'Mean', 'Population', 'Median']

In [ ]:
# Dropping multiple columns -- do this to simplify the .describes above -- from Cleaning Practice with Josh 
#water_to_income_df.drop(['FY 05/06','FY 06/07'], axis=1, inplace=True)